name: Danger CI

on: [pull_request, merge_group]

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Danger main check
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: |
          npm install --save-dev @babel/plugin-transform-flow-strip-types
      - name: Danger
        uses: danger/danger-js@a236e3b8c41f0babbf133568db851a20a34f9a7b # 14.0.5
        with:
          args: "--dangerfile ./tools/danger/dangerfile.js"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
